version: "3.8"
services:
    ngnix:
        image: "nginx"
        restart: "always"
        networks:
            - sigma_net
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - /etc/letsencrypt:/etc/letsencrypt
        ports:
            - 80:80
            - 443:443
    mongodb:
        image: "mongo"
        restart: "always"
        networks:
            - sigma_net
        volumes:
            - data:/data/db
        ports:
            - "27107:27107"
        environment:
            MONGO_INITDB_ROOT_USERNAME: Sigma
            MONGO_INITDB_ROOT_PASSWORD: Experi2ma
    mongo-express:
        image: mongo-express
        restart: always
        networks:
            - sigma_net
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: Sigma
            ME_CONFIG_MONGODB_ADMINPASSWORD: Experi2ma
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_BASICAUTH_USERNAME: Sigma
            ME_CONFIG_BASICAUTH_PASSWORD: Laviosa-n654321
    makkie:
        build: "./makkie"
        ports:
            - "5000:5000"
        restart: always
        networks:
            - sigma_net
        volumes:
            - /app/node_modules
        depends_on:
            - mongodb
    medsoph:
        build: "./medsoph"
        ports:
            - "4000:4000"
        restart: always
        networks:
            - sigma_net
        volumes:
            - /app/node_modules
        stdin_open: true
        tty: true
        depends_on:
            - mongodb
    makkie_fd:
        build: "./makkie_fd/"
        ports:
            - "7000:80"
        restart: always
        networks:
            - sigma_net
        volumes:
            - ./makkie_fd/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - makkie
    medsoph_fd:
        build: "./medsoph_fd/"
        ports:
            - "8000:80"
        restart: always
        networks:
            - sigma_net
        volumes:
            - ./medsoph_fd/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - medsoph
    personal:
        build: "./Personal"
        ports:
            - "3000:3000"
        restart: always
        networks:
            - sigma_net
        stdin_open: true
        tty: true
networks:
    sigma_net:
        # external: true
        # name: sigma_net
volumes:
    data:
        # external: true
        # name: storage
